module.exports = {
    content: ['./src/**/*.{html,js,jsx,ts,tsx,vue}'],
    prefix: '',
    theme: {
        container: {
            center: true,
            padding: '2rem',
            screens: {
                '2xl': '1400px',
            },
        },
        extend: {
            colors: {
                border: 'hsl(var(--border))',
                input: 'hsl(var(--input))',
                ring: 'hsl(var(--ring))',
                background: 'hsl(var(--background))',
                foreground: 'hsl(var(--foreground))',
                customBlue: '#6D84F2',
                primary: {
                    DEFAULT: 'hsl(var(--primary))',
                    foreground: 'hsl(var(--primary-foreground))',
                    50: 'var(--primary-50)',
                    100: 'var(--primary-100)',
                    200: 'var(--primary-200)',
                    300: 'var(--primary-300)',
                    400: 'var(--primary-400)',
                    500: 'var(--primary-500)',
                    600: 'var(--primary-600)',
                    700: 'var(--primary-700)',
                    800: 'var(--primary-800)',
                    900: 'var(--primary-900)',
                },
                secondary: {
                    DEFAULT: 'hsl(var(--secondary))',
                    foreground: 'hsl(var(--secondary-foreground))',
                    50: 'var(--secondary-50)',
                    100: 'var(--secondary-100)',
                    200: 'var(--secondary-200)',
                    300: 'var(--secondary-300)',
                    400: 'var(--secondary-400)',
                    500: 'var(--secondary-500)',
                    600: 'var(--secondary-600)',
                    700: 'var(--secondary-700)',
                    800: 'var(--secondary-800)',
                    900: 'var(--secondary-900)',
                },
                tertiary: {
                    50: 'var(--tertiary-50)',
                    100: 'var(--tertiary-100)',
                    200: 'var(--tertiary-200)',
                    300: 'var(--tertiary-300)',
                    400: 'var(--tertiary-400)',
                    500: 'var(--tertiary-500)',
                    600: 'var(--tertiary-600)',
                    700: 'var(--tertiary-700)',
                    800: 'var(--tertiary-800)',
                    900: 'var(--tertiary-900)',
                },
                success: {
                    50: 'var(--success-50)',
                    100: 'var(--success-100)',
                    200: 'var(--success-200)',
                    300: 'var(--success-300)',
                    400: 'var(--success-400)',
                    500: 'var(--success-500)',
                    600: 'var(--success-600)',
                    700: 'var(--success-700)',
                    800: 'var(--success-800)',
                    900: 'var(--success-900)',
                },
                error: {
                    50: 'var(--error-50)',
                    100: 'var(--error-100)',
                    200: 'var(--error-200)',
                    300: 'var(--error-300)',
                    400: 'var(--error-400)',
                    500: 'var(--error-500)',
                    600: 'var(--error-600)',
                    700: 'var(--error-700)',
                    800: 'var(--error-800)',
                    900: 'var(--error-900)',
                },
                warning: {
                    50: 'var(--warning-50)',
                    100: 'var(--warning-100)',
                    200: 'var(--warning-200)',
                    300: 'var(--warning-300)',
                    400: 'var(--warning-400)',
                    500: 'var(--warning-500)',
                    600: 'var(--warning-600)',
                    700: 'var(--warning-700)',
                    800: 'var(--warning-800)',
                    900: 'var(--warning-900)',
                },
            },
            borderRadius: {
                1: 'var(--border-radius-1)',
                2: 'var(--border-radius-2)',
                3: 'var(--border-radius-3)',
                4: 'var(--border-radius-4)',
                5: 'var(--border-radius-5)',
                6: 'var(--border-radius-6)',
                7: 'var(--border-radius-7)',
                8: 'var(--border-radius-8)',
                9: 'var(--border-radius-9)',
            },
            spacing: {
                1: 'var(--spacing-1)',
                2: 'var(--spacing-2)',
                3: 'var(--spacing-3)',
                4: 'var(--spacing-4)',
                5: 'var(--spacing-5)',
                6: 'var(--spacing-6)',
                7: 'var(--spacing-7)',
                8: 'var(--spacing-8)',
                10: 'var(--spacing-10)',
                12: 'var(--spacing-12)',
                14: 'var(--spacing-14)',
                16: 'var(--spacing-16)',
                20: 'var(--spacing-20)',
                24: 'var(--spacing-24)',
                25: 'var(--spacing-25)',
                28: 'var(--spacing-28)',
            },
            boxShadow: {
                1: 'var(--elevation-1)',
                2: 'var(--elevation-2)',
                3: 'var(--elevation-3)',
                4: 'var(--elevation-4)',
                5: 'var(--elevation-5)',
                6: 'var(--elevation-6)',
            },
            fontSize: {
                caption: 'var(--font-size-caption)',
                body1: 'var(--font-size-body1)',
                subtitle1: 'var(--font-size-subtitle1)',
                body2: 'var(--font-size-body2)',
                subtitle2: 'var(--font-size-subtitle2)',
                h6: 'var(--font-size-h6)',
                h5: 'var(--font-size-h5)',
                h4: 'var(--font-size-h4)',
                h3: 'var(--font-size-h3)',
                h2: 'var(--font-size-h2)',
                h1: 'var(--font-size-h1)',
            },
            lineHeight: {
                body1: 'var(--line-height-body1)',
                caption: 'var(--line-height-caption)',
                subtitle1: 'var(--line-height-subtitle1)',
                body2: 'var(--line-height-body2)',
                subtitle2: 'var(--line-height-subtitle2)',
                h6: 'var(--line-height-h6)',
                h5: 'var(--line-height-h5)',
                h4: 'var(--line-height-h4)',
                h3: 'var(--line-height-h3)',
                h2: 'var(--line-height-h2)',
                h1: 'var(--line-height-h1)',
            },
            destructive: {
                DEFAULT: 'hsl(var(--destructive))',
                foreground: 'hsl(var(--destructive-foreground))',
            },
            muted: {
                DEFAULT: 'hsl(var(--muted))',
                foreground: 'hsl(var(--muted-foreground))',
            },
            accent: {
                DEFAULT: 'hsl(var(--accent))',
                foreground: 'hsl(var(--accent-foreground))',
            },
            popover: {
                DEFAULT: 'hsl(var(--popover))',
                foreground: 'hsl(var(--popover-foreground))',
            },
            card: {
                DEFAULT: 'hsl(var(--card))',
                foreground: 'hsl(var(--card-foreground))',
            },
        },
        keyframes: {
            'accordion-down': {
                from: { height: '0' },
                to: { height: 'var(--radix-accordion-content-height)' },
            },
            'accordion-up': {
                from: { height: 'var(--radix-accordion-content-height)' },
                to: { height: '0' },
            },
        },
        animation: {
            'accordion-down': 'accordion-down 0.2s ease-out',
            'accordion-up': 'accordion-up 0.2s ease-out',
        },
    },
    plugins: [require('tailwindcss-animate')],
};
